# Generated by Django 3.2 on 2022-12-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128)),
                ('customer_email', models.CharField(max_length=128)),
                ('customer_question_text_body', models.TextField(blank=True, null=True)),
                ('company_answer_text_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(default=None, max_length=255)),
                ('review_text_body', models.TextField(default=None)),
                ('picture_s3_url', models.CharField(blank=True, max_length=128, null=True)),
                ('video_s3_url', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_name', models.CharField(default=None, max_length=128)),
                ('customer_email', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=128)),
                ('product_manufacturer', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
                ('product_SKU', models.CharField(max_length=32)),
                ('product_condition', models.CharField(choices=[('new', 'new'), ('refurbished', 'refurbished')], max_length=64)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_in_stock', models.BooleanField(default=True)),
                ('product_quantity', models.IntegerField()),
                ('product_on_sale', models.BooleanField(default=False)),
                ('product_manuals_and_documentation', models.CharField(blank=True, max_length=128, null=True)),
                ('product_overview', jsonfield.fields.JSONField(blank=True, null=True)),
                ('product_features', jsonfield.fields.JSONField(blank=True, null=True)),
                ('product_specifications', jsonfield.fields.JSONField(blank=True, null=True)),
                ('product_warranty_additional_information', jsonfield.fields.JSONField(blank=True, null=True)),
                ('product_photos', models.CharField(blank=True, max_length=128, null=True)),
                ('product_videos', models.CharField(blank=True, max_length=128, null=True)),
                ('product_discounted', models.BooleanField(default=False)),
                ('product_discounted_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_package_contents', jsonfield.fields.JSONField(blank=True, null=True)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
                ('generator_classification_type', models.CharField(choices=[('portable', 'portable'), ('standby', 'standby'), ('inverter', 'inverter')], max_length=128)),
                ('generator_fuel_type', models.CharField(max_length=64)),
                ('generator_continuous_wattage_value', models.IntegerField()),
                ('product_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productquestion')),
                ('product_reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productreview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
