# Generated by Django 3.2 on 2022-12-26 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDecor',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.baseproduct')),
                ('home_decor_classification_type', models.CharField(choices=[('Furniture', 'Furniture'), ('Outdoor_and_Garden', 'Outdoor_and_Garden'), ('Bedding', 'Bedding'), ('Bath', 'Bath'), ('Lighting', 'Lighting'), ('Rugs', 'Rugs'), ('Windows', 'Windows'), ('Pillows_and_Decor', 'Pillows_and_Decor'), ('Art_and_Mirrors', 'Art_and_Mirrors'), ('Tabletop_and_Bar', 'Tabletop_and_Bar'), ('Storage', 'Storage'), ('Holidays', 'Holidays'), ('Gifts', 'Gifts')], max_length=64)),
            ],
            bases=('ecommerce.baseproduct',),
        ),
    ]
