# Generated by Django 3.2 on 2022-12-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20221205_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='product_photos',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='product_videos',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
