# Generated by Django 3.2 on 2022-12-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20221205_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='product_photos',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='product_videos',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
