# Generated by Django 3.2 on 2022-12-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecommerce', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameconsole',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='generator',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='homedecor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ecommerce.baseproduct_set+', to='contenttypes.contenttype'),
        ),
    ]
