# Generated by Django 3.2 on 2022-12-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_cartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsNutrition',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.baseproduct')),
                ('sports_nutrition_classification_type', models.CharField(choices=[('Supplements', 'Supplements'), ('Vitamins', 'Vitamins'), ('Keto', 'Keto'), ('Weight_Support', 'Weight_Support'), ('Energy', 'Energy'), ('Cleanse', 'Cleanse'), ('Muscle_Support', 'Muscle_Support'), ('Digestive_Support', 'Digestive_Support'), ('Gel', 'Gel'), ('Powder', 'Powder'), ('Capsule', 'Capsule')], max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ecommerce.baseproduct',),
        ),
    ]
