# Generated by Django 3.2 on 2022-12-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20221211_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='stripe_product_id',
            field=models.CharField(default='price_1MFnyKJeoQWEr4BM36XT0Q5y', max_length=100),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.generator')),
            ],
        ),
    ]
