# Generated by Django 3.2 on 2022-12-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20221217_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_count_FK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.generator'),
        ),
        migrations.AddField(
            model_name='generator',
            name='product_count_in_user_cart',
            field=models.IntegerField(default=0),
        ),
    ]
