# Generated by Django 3.2 on 2022-12-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_sportsnutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenAndHomeAppliance',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.baseproduct')),
                ('kitchen_and_home_appliance_classification_type', models.CharField(choices=[('Air Fryer', 'Air Fryer'), ('Oven', 'Oven'), ('Toaster', 'Toaster'), ('Microwave', 'Microwave'), ('Television', 'Television'), ('Coffee Maker', 'Coffee Maker'), ('Air Conditioner', 'Air Conditioner'), ('Dishwasher', 'Dishwasher'), ('Clothes Washer', 'Clothes Washer'), ('Clothes Dryer', 'Clothes Dryer'), ('Water Heater', 'Water Heater')], max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ecommerce.baseproduct',),
        ),
    ]
