# Generated by Django 3.2 on 2022-12-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_kitchenandhomeappliance_kitchen_and_home_appliance_classification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.baseproduct'),
        ),
    ]
