# Generated by Django 3.2 on 2022-12-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20221228_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
