# Generated by Django 3.2 on 2023-01-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20230102_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
