# Generated by Django 3.2 on 2023-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20230102_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_category',
            field=models.CharField(max_length=128),
        ),
    ]
