# Generated by Django 3.2 on 2023-01-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_baseproduct_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
