# Generated by Django 3.2 on 2023-01-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_baseproduct_product_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_package_contents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_specifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_warranty_additional_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
