# Generated by Django 3.2 on 2023-01-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20230104_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='product_package_contents',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='product_warranty_additional_information',
        ),
    ]
