# Generated by Django 3.2 on 2023-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20230104_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='product_rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
