# Generated by Django 3.2 on 2023-01-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20230107_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='review_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='review_updated_at',
            new_name='updated_at',
        ),
    ]
