# Generated by Django 3.2 on 2023-01-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0028_auto_20230107_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
