# Generated by Django 3.2 on 2023-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_auto_20230107_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
