# Generated by Django 3.2 on 2023-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20230107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_completed',
            field=models.BooleanField(default=False),
        ),
    ]
