# Generated by Django 3.2 on 2023-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_delivery_delivery_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='oauth_user_id',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
