# Generated by Django 3.2 on 2023-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_customer_oauth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
