from ecommerce.models import KitchenAndHomeAppliance, GameConsole, Generator, SportsNutrition, HomeDecor
from django.core.management.base import BaseCommand
from django.db import transaction
from faker import Faker
fake = Faker()

class Command(BaseCommand):

  help = "Adds an overview to all existing products"

  @transaction.atomic
  def handle(self, *args, **kwargs):
    self.stdout.write("Generating an overview to all existing products")

    all_products_overview = """This is overview data for a particular product. I have generated this data randomly 
    so that I may simulate the overview portion for an item of my ecommerce POC. I have used factory-boy to 
    generate all of my random test data. This is why you will sometimes see images and product names that 
    do not correctly align. However, this helps me with my unit tests so that I can cover edge cases more
    easily, instead of just generating the same content for each product. It's also extremely easy to 
    tear-down and spin-up all of my test data at scale. I have a multitude of scripts that I have written 
    to handle all of this atomically. """

    kitchen_and_home_appliances = KitchenAndHomeAppliance.objects.all()
    for kitchen_and_home_appliance in kitchen_and_home_appliances:
      build_overview = 'This is a Kitchen and Home Appliance Product Overview. '
      build_overview += all_products_overview
      build_overview += 'Following this sentence will be some random text generated by factory-boy for unit tests. '
      for i in range(5):
        build_overview += ' ' + fake.text()
      kitchen_and_home_appliance.product_overview = build_overview
      kitchen_and_home_appliance.save()

    for game_console in GameConsole.objects.all():
      build_overview = 'This is a Game Console Product Overview. '
      build_overview += all_products_overview
      build_overview += 'Following this sentence will be some random text generated by factory-boy for unit tests. '
      for i in range(5):
        build_overview += ' ' + fake.text()
      game_console.product_overview = build_overview
      game_console.save()

    for generator in Generator.objects.all():
      build_overview = 'This is a Generator Product Overview. '
      build_overview += all_products_overview
      build_overview += 'Following this sentence will be some random text generated by factory-boy for unit tests. '
      for i in range(5):
        build_overview += ' ' + fake.text()
      generator.product_overview = build_overview
      generator.save()
    
    for sports_and_nutrition in SportsNutrition.objects.all():
      build_overview = 'This is a Sports Nutrition Product Overview. '
      build_overview += all_products_overview
      build_overview += 'Following this sentence will be some random text generated by factory-boy for unit tests. '
      for i in range(5):
        build_overview += ' ' + fake.text()
      sports_and_nutrition.product_overview = build_overview
      sports_and_nutrition.save()

    for home_decor in HomeDecor.objects.all():
      build_overview = 'This is a Home Decor Product Overview. '
      build_overview += all_products_overview
      build_overview += 'Following this sentence will be some random text generated by factory-boy for unit tests. '
      for i in range(5):
        build_overview += ' ' + fake.text()
      home_decor.product_overview = build_overview
      home_decor.save()